# Workflow to create a release
name: Release 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/build.gradle'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Check for version change
        id: check
        run: |
          git fetch
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            DIFF=$(git diff HEAD^ HEAD -- app/build.gradle)
            if echo "$DIFF" | grep -q "+version"; then
              echo "Version changed"
              echo "::set-output name=version_changed::true"
            else
              echo "Version did not change"
              echo "::set-output name=version_changed::false"
            fi
          else
            echo "No previous commit to compare against"
            echo "::set-output name=version_changed::false"
          fi

      - name: Extract version
        id: extract
        run: |
          if [ "${{ steps.check.outputs.version_changed }}" = "true" ]; then
            VERSION=$(grep "^version '" app/build.gradle | awk '{print $2}' | tr -d \')
            echo "::set-output name=version::$VERSION"
          else
            echo "::set-output name=version::"
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract.outputs.version }}
          release_name: Frequent Pattern Mining - ${{ steps.extract.outputs.version }}
          draft: true
          prerelease: false
